version: "2"
services:
  # Test app to generate traces
  hotrod:
    image: jaegertracing/example-hotrod:latest
    command: ["all"]
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
    ports: 
      - "8080:8080"
    depends_on:
      - otel
      - jaeger
    networks:
      - telemetry

  # Collect traces
  otel:
    image: otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_TAG:-0.48.0}
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "6831:6831" # Jaeger thrift compact
    networks:
      - telemetry

  # Store & show traces
  # see https://www.jaegertracing.io/docs/1.32/deployment/#all-in-one
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_TAG:-latest}
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGET_DIRECTORY_KEY: /badger/key
    volumes:
      - "jaeger:/badger"
    ports:
      - "14250:14250" # gRPC ingestion
      - "16686:16686" # UI
    networks:
      - telemetry

volumes:
  jaeger:
    driver: local

networks:
  telemetry:
    driver: bridge
